/**
 * Quality Review skill template — adapted for distribution.
 *
 * Adapted from .claude/skills/quality-review/SKILL.md:
 * - loads: references organon/ETHOS.md and CLAUDE.md (not book-llms/)
 * - Anti-pattern checklist embedded in body
 */

export const QUALITY_REVIEW_SKILL = [
  '---',
  'name: quality-review',
  'description: Semantic review of organon files that goes beyond automated gates. Checks whether invariants are testable, principles are genuinely prioritized, identity statements define real boundaries, and heuristics cover actual recurring decisions. Use for quality checks or when reviewing new organon files.',
  'protocol_id: PROTO-ORG-7',
  'protocol_file: organon/protocols/PROTOCOLS.md',
  'tools: [organon-verify, organon-validate, organon-health]',
  'loads:',
  '  - organon/ETHOS.md',
  '  - CLAUDE.md',
  'methodology_version: "0.5.2"',
  '---',
  '',
  '# Quality Review Workflow',
  '',
  '> Semantic quality review that catches what automation cannot.',
  '',
  '## Methodology Context',
  '',
  'This workflow extends the **Verify** step of the Organon enforcement loop with semantic checks that automated gates cannot perform — ensuring invariants are testable, principles genuinely prioritized, and identity statements define real boundaries. For methodology background, read `organon/PRIMER.md`.',
  '',
  '---',
  '',
  '## When to Use This Skill',
  '',
  'Use this skill when:',
  '- **Reviewing new organon files** — before merging',
  '- **Periodic quality audits** — beyond automated gates',
  '- **After significant methodology changes** — verify meaning wasn\'t lost',
  '',
  '---',
  '',
  '## Steps',
  '',
  '### Step 1: Run Automated Gates First',
  '',
  '    organon verify',
  '    organon validate <path>',
  '',
  'Fix automated failures before semantic review.',
  '',
  '### Step 2: Review Invariants',
  '',
  'For each invariant, apply these filters:',
  '',
  '| Filter | Question | Pass Criteria |',
  '|--------|----------|---------------|',
  '| **Testable?** | Can you write a gate for this? | Yes |',
  '| **Specific?** | Does this constrain concretely? | Not vague |',
  '| **Enforceable?** | Is enforcement real? | References a tool or gate |',
  '| **Non-redundant?** | Adds value beyond parent? | Yes |',
  '',
  '**Red flags:** "Should be high quality" (too vague), "Enforced by: reviews" (too weak).',
  '',
  '### Step 3: Review Principle Ordering',
  '',
  '1. **Conflict test:** If principle 3 conflicts with principle 1, does 1 genuinely win?',
  '2. **Independence test:** Are any two principles saying the same thing?',
  '3. **Actionability test:** Can an agent use this ordering to make decisions?',
  '',
  '### Step 4: Review Identity Statements',
  '',
  '| Check | Good | Bad |',
  '|-------|------|-----|',
  '| **Specific?** | "A semantic testing framework for tier-4 verification" | "A good testing framework" |',
  '| **Distinguishing?** | Only describes THIS thing | Could describe any similar thing |',
  '| **Boundary-defining?** | IS NOT prevents scope creep | IS NOT is obvious negation |',
  '',
  '### Step 5: Review Heuristics',
  '',
  '- Do they cover decisions that actually recur?',
  '- Are there common decisions missing?',
  '- Are actions specific enough to follow?',
  '',
  '### Step 6: Check Anti-Patterns',
  '',
  'Common anti-patterns to check for:',
  '',
  '| Anti-Pattern | Symptom | Fix |',
  '|-------------|---------|-----|',
  '| Phantom Enforcement | Invariant claims enforcement but mechanism doesn\'t exist | Add real enforcement mechanism |',
  '| Aspiration as Invariant | "Should be" language in invariant | Rewrite as "must be" with enforcement |',
  '| Context Overload | Workflow loads too many files | Reduce to essential files only |',
  '| Missing Error Recovery | No failure/recovery table | Add error recovery section |',
  '| Scope Creep | IS NOT section doesn\'t define boundaries | Add specific IS NOT statements |',
  '',
  '### Step 7: Generate Review Report',
  '',
  '    ## Quality Review Report',
  '',
  '    ### Errors (must fix)',
  '    - [file:line] - [finding] - [fix]',
  '',
  '    ### Warnings (should fix)',
  '    - [file:line] - [finding] - [fix]',
  '',
  '    ### Summary',
  '    - Files reviewed: N',
  '    - Errors: N, Warnings: N',
  '',
  '---',
  '',
  '## Verification',
  '',
  '- [ ] All automated gates pass (prerequisite)',
  '- [ ] Every invariant passes "testable?" filter',
  '- [ ] Principle ordering is defensible',
  '- [ ] Identity statements are specific and distinguishing',
  '- [ ] No anti-pattern matches found',
  '',
  '---',
  '',
  '## Error Recovery',
  '',
  '| Failure | Recovery Action |',
  '|---------|-----------------|',
  '| Invariant untestable | Rewrite more specifically, or move to principles. |',
  '| Principles not prioritized | Reorder with explicit trade-off reasoning. |',
  '| Identity too generic | Add specifics: technology names, scope boundaries. |',
  '| Anti-pattern found | Apply fix from anti-pattern table. |',
  '| Too many findings | Prioritize errors over warnings. Fix errors first. |',
  '',
].join('\n');
