/**
 * Session Compounding skill template — adapted for distribution.
 *
 * Adapted from .claude/skills/session-compounding/SKILL.md:
 * - loads: references CLAUDE.md and organon/observations/README.md
 * - Pattern guidance embedded in body
 */

export const SESSION_COMPOUNDING_SKILL = [
  '---',
  'name: session-compounding',
  'description: Reviews a work session\'s output to detect improvable patterns, classify improvements, and execute the highest-priority one. Use at the end of significant work sessions to ensure compounding happens. Without explicit compounding, improvement never happens.',
  'protocol_id: PROTO-ORG-5',
  'protocol_file: organon/protocols/PROTOCOLS.md',
  'tools: [organon-verify, organon-health, organon-find]',
  'loads:',
  '  - CLAUDE.md',
  '  - organon/observations/README.md',
  'methodology_version: "0.4.0"',
  '---',
  '',
  '# Session Compounding Workflow',
  '',
  '> Converts session learnings into durable improvements.',
  '',
  '## Methodology Context',
  '',
  'This workflow implements the **Compound** step of the Organon enforcement loop. Without explicit compounding, improvement never happens — session learnings are lost between contexts. This workflow detects patterns, classifies improvements, and executes the highest-priority one. For methodology background, read `organon/PRIMER.md`.',
  '',
  '---',
  '',
  '## When to Use This Skill',
  '',
  'Use this skill when:',
  '- **Ending a significant work session** — substantial changes were made',
  '- **After completing a multi-step task** — new patterns may have emerged',
  '- **After encountering friction** — something was harder than it should have been',
  '',
  '---',
  '',
  '## Steps',
  '',
  '### Step 1: Review Session Work',
  '',
  '    git diff --stat HEAD~N  # N = commits in this session',
  '    git log --oneline -N',
  '',
  'List files created/modified, types of changes, and patterns in the work.',
  '',
  '### Step 2: Detect Patterns',
  '',
  '| Signal | Example | Indicates |',
  '|--------|---------|-----------|',
  '| **Repeated manual steps** | Same 3 commands every time | Tool candidate |',
  '| **Unclear workflow** | Wasn\'t sure which skill to use | Workflow gap |',
  '| **New heuristic** | Same decision made repeatedly | Heuristic addition |',
  '| **Awkward tool usage** | Same command 3 different ways | Tool improvement |',
  '| **Missing context** | Needed 5 files, skill listed 3 | Workflow context update |',
  '| **Error without guidance** | Tool failed, didn\'t know fix | Error recovery addition |',
  '',
  '### Step 3: Classify Improvements',
  '',
  '| Category | Where to Implement |',
  '|----------|-------------------|',
  '| **Tool candidate** | `packages/tools/` — new command or flag |',
  '| **Protocol update** | `organon/protocols/PROTOCOLS.md` |',
  '| **Heuristic addition** | `CLAUDE.md` or `organon/ETHOS.md` |',
  '| **Workflow refinement** | `.claude/skills/<name>/SKILL.md` |',
  '',
  '### Step 4: Prioritize',
  '',
  '    Priority = How often does this recur? x How much friction does it cause?',
  '',
  '| Frequency | Impact | Priority |',
  '|-----------|--------|----------|',
  '| Every session | Blocks work | Highest — do now |',
  '| Weekly | Slows work | High — do this session |',
  '| Monthly | Annoying | Medium — create RFC |',
  '| Rare | Minor | Low — note for future |',
  '',
  '### Step 5: Execute Improvement',
  '',
  'With user confirmation, implement the highest-priority improvement.',
  '',
  '### Step 6: Run Verification',
  '',
  '    organon verify',
  '    organon health',
  '',
  'Confirm no regressions.',
  '',
  '### Step 7: Record Observations (Optional)',
  '',
  'If the session produced observations worth preserving:',
  '- An active observation file covers this topic \u2192 add to it',
  '- No relevant file \u2192 create new `organon/observations/NNN-descriptive-name.md`',
  '',
  'Each observation needs: Signal (what happened), Implication (what it means), Suggested Action (what to do).',
  '',
  '**Not every session produces observations — that\'s fine.**',
  '',
  '---',
  '',
  '## Verification',
  '',
  '- [ ] At least one improvement identified and classified',
  '- [ ] Highest-priority improvement either executed or documented',
  '- [ ] `organon verify` passes after any changes',
  '- [ ] `organon health` score has not decreased',
  '',
  '---',
  '',
  '## Error Recovery',
  '',
  '| Failure | Recovery Action |',
  '|---------|-----------------|',
  '| No patterns detected | Session may have been too small. Note for next session. |',
  '| Improvement breaks verification | Revert. Re-analyze the approach. |',
  '| User declines execution | Document as TODO or RFC for future. |',
  '| Too many improvements | Execute only highest-priority. Document the rest. |',
  '',
].join('\n');
