/**
 * CLAUDE.md scaffold template for organon init.
 *
 * This is the standard Claude Code project instructions file.
 * Enriched with methodology context so agents understand
 * what Organon is, not just what commands to run.
 */

export const CLAUDE_MD_TEMPLATE = [
  '# Project Instructions',
  '',
  '> Agent guidance for this project. Loaded automatically by Claude Code.',
  '',
  '---',
  '',
  '## Organon Methodology',
  '',
  'This project uses the [Organon methodology](https://github.com/VledicFranco/organon) for behavioral consistency in human-LLM collaboration. Organon files define constraints (ETHOS.md), design rationale (PHILOSOPHY.md), and procedures (PROTOCOLS.md) that guide development. The methodology is enforced through an automated loop:',
  '',
  '    Define → Bind → Execute → Verify',
  '',
  '---',
  '',
  '## Quick Reference',
  '',
  '- Read `organon/ETHOS.md` before working in this codebase',
  '- Run `organon verify` before committing (checks 7 gates: frontmatter, references, triplets, placeholder-detection, freshness, invariant-coverage, version-alignment)',
  '- Run `organon health` for aggregate project integrity score (0-100)',
  '',
  '---',
  '',
  '## When Verify Fails',
  '',
  'Each failure includes a diagnostic code. Common fixes:',
  '',
  '| Code | Fix |',
  '|------|-----|',
  '| `FRONTMATTER_MISSING` | Add YAML frontmatter (use `organon generate <path>`) |',
  '| `FRONTMATTER_COUNT_MISMATCH` | Update count fields to match actual content |',
  '| `INVARIANT_UNCOVERED` | Add a test with `// @organon-invariant INV-ID` annotation |',
  '| `REFERENCE_BROKEN` | Fix broken file path in `inherits_from` or `related_files` |',
  '| `PLACEHOLDER_DETECTED` | Replace template placeholders with real content |',
  '',
  '---',
  '',
  '## Decision Heuristics',
  '',
  '| Situation | Action |',
  '|-----------|--------|',
  '| Starting a work session | Run `organon verify` for baseline check |',
  '| Before committing | Run `organon verify` to ensure nothing is broken |',
  '| Creating organon files | Use `/organon-file-creation` skill |',
  '| Reviewing organon quality | Use `/quality-review` skill |',
  '',
  '---',
  '',
  '## First Session Setup',
  '',
  'If `organon/ETHOS.md` still contains template placeholders:',
  '',
  "1. Replace `organon/ETHOS.md` with your project's real constraints",
  '2. Replace `organon/PHILOSOPHY.md` with real design rationale',
  '3. Run `organon verify` and fix any issues',
  '4. Run `organon health` — target score 80+',
  '',
].join('\n');
