/**
 * CLAUDE.md scaffold template for organon init.
 *
 * This is the standard Claude Code project instructions file.
 * Enriched with methodology context so agents understand
 * what Organon is, not just what commands to run.
 */

export const CLAUDE_MD_TEMPLATE = [
  '# Project Instructions',
  '',
  '> Agent guidance for this project. Loaded automatically by Claude Code.',
  '',
  '---',
  '',
  '## Organon Methodology',
  '',
  'This project uses the [Organon methodology](https://github.com/VledicFranco/organon) for behavioral consistency in human-LLM collaboration. Organon files define constraints (ETHOS.md), design rationale (PHILOSOPHY.md), and procedures (PROTOCOLS.md) that guide development. The methodology is enforced through an automated loop:',
  '',
  '    Define → Bind → Execute → Verify → Compound → Evolve',
  '',
  '---',
  '',
  '## Quick Reference',
  '',
  '- Read `organon/PRIMER.md` to understand the methodology (first session)',
  '- Read `organon/ETHOS.md` before working in this codebase',
  '- Run `organon verify` before committing (checks 9 gates: frontmatter, triplets, references, placeholders, freshness, invariant coverage, workflow quality, tier4 tests, version alignment)',
  '- Run `organon health` for aggregate project integrity score (0-100)',
  '',
  '---',
  '',
  '## When Verify Fails',
  '',
  'Each failure includes a diagnostic code. Common fixes:',
  '',
  '| Code | Fix |',
  '|------|-----|',
  '| `FRONTMATTER_MISSING` | Add YAML frontmatter (use `organon generate <path>`) |',
  '| `FRONTMATTER_COUNT_MISMATCH` | Update count fields to match actual content |',
  '| `WORKFLOW_MISSING_TOOLS` | Add `tools:` array to skill frontmatter |',
  '| `REFERENCE_BROKEN_LOADS` | Fix file path in workflow `loads:` array |',
  '| `PLACEHOLDER_DETECTED` | Replace template placeholders with real content |',
  '',
  'For full diagnostic code reference: read `organon/methodology-reference.md`.',
  '',
  '---',
  '',
  '## Decision Heuristics',
  '',
  '| Situation | Action |',
  '|-----------|--------|',
  '| Starting a work session | Run `organon verify` for baseline check |',
  '| Before committing | Run `organon verify` to ensure nothing is broken |',
  '| Adding a new domain | Use `/domain-feature-design` skill |',
  '| Creating organon files | Use `/organon-file-creation` skill |',
  '| Reviewing organon quality | Use `/quality-review` skill |',
  '| End of work session | Use `/session-compounding` skill |',
  '',
  '---',
  '',
  '## First Session Setup',
  '',
  'If `organon/ETHOS.md` still contains template placeholders:',
  '',
  '1. Read `organon/PRIMER.md` to understand the methodology',
  "2. Replace `organon/ETHOS.md` with your project's real constraints",
  '3. Replace `organon/PHILOSOPHY.md` with real design rationale',
  '4. Run `organon verify` and fix any issues',
  '5. Run `organon health` — target score 80+',
  '',
].join('\n');
