/**
 * PROTOCOLS.md scaffold template for organon init.
 *
 * Contains 5 generic protocols matching the 5 distributable skills.
 */

export const PROTOCOLS_TEMPLATE = [
  '---',
  'type: procedures',
  'scope: product',
  'name: protocols',
  'version: "1.0"',
  'summary: Development protocols for this project — step-by-step procedures with workflow bindings',
  'token_estimate: 2400',
  'protocols_count: 5',
  'protocols:',
  '  - id: PROTO-ORG-1',
  '    name: RFC-Driven Design',
  '    steps: 6',
  '    automation_tier: automated',
  '    workflow: domain-feature-design',
  '    tools: [organon-validate, organon-verify]',
  '    complexity: high',
  '  - id: PROTO-ORG-4',
  '    name: Verification and Health',
  '    steps: 5',
  '    automation_tier: automated',
  '    workflow: verify-and-health',
  '    tools: [organon-verify, organon-health]',
  '    complexity: low',
  '  - id: PROTO-ORG-5',
  '    name: Session Compounding',
  '    steps: 7',
  '    automation_tier: automated',
  '    workflow: session-compounding',
  '    tools: [organon-verify, organon-health, organon-find]',
  '    complexity: medium',
  '  - id: PROTO-ORG-6',
  '    name: Organon File Creation',
  '    steps: 8',
  '    automation_tier: automated',
  '    workflow: organon-file-creation',
  '    tools: [organon-generate, organon-validate, organon-verify]',
  '    complexity: medium',
  '  - id: PROTO-ORG-7',
  '    name: Quality Review',
  '    steps: 7',
  '    automation_tier: automated',
  '    workflow: quality-review',
  '    tools: [organon-verify, organon-validate, organon-health]',
  '    complexity: high',
  'audience: [llm, human, tooling]',
  '---',
  '',
  '# Development Protocols',
  '',
  '> Step-by-step procedures for development activities. Each protocol has a corresponding workflow (skill) binding.',
  '',
  '---',
  '',
  '## Protocol Overview',
  '',
  '| ID | Name | Workflow | Complexity |',
  '|----|------|----------|------------|',
  '| PROTO-ORG-1 | RFC-Driven Design | domain-feature-design | High |',
  '| PROTO-ORG-4 | Verification and Health | verify-and-health | Low |',
  '| PROTO-ORG-5 | Session Compounding | session-compounding | Medium |',
  '| PROTO-ORG-6 | Organon File Creation | organon-file-creation | Medium |',
  '| PROTO-ORG-7 | Quality Review | quality-review | High |',
  '',
  '---',
  '',
  '## PROTO-ORG-1: RFC-Driven Design',
  '',
  '> Design new domains and features using RFC-Driven Evolution.',
  '',
  '### Goal',
  '',
  'Produce a complete RFC with both organon mutation plan and technical implementation plan.',
  '',
  '### Steps',
  '',
  '1. **Load context.** Read organon/ETHOS.md and CLAUDE.md.',
  '2. **Classify scope.** Domain (bounded context), feature (cross-cutting), or component.',
  '3. **Create RFC.** Determine next number, create rfcs/NNN-name.md.',
  '4. **Write organon plan.** Exact ETHOS.md and PHILOSOPHY.md content.',
  '5. **Write technical plan.** Architecture, API, implementation phases.',
  '6. **Self-review.** Both plans present, invariants testable, principles prioritized.',
  '',
  '### Verification',
  '',
  '- [ ] RFC has both organon and technical plans',
  '- [ ] Invariants are testable',
  '- [ ] `organon validate` passes on RFC',
  '',
  '---',
  '',
  '## PROTO-ORG-4: Verification and Health',
  '',
  '> Run all verification gates and health checks.',
  '',
  '### Goal',
  '',
  'Confirm project integrity with actionable fix guidance.',
  '',
  '### Steps',
  '',
  '1. **Run verification.** `organon verify` (all gates).',
  '2. **Run health.** `organon health` for overall score.',
  '3. **Interpret failures.** Map each to specific fix.',
  '4. **Apply fixes.** Edit specific files and fields.',
  '5. **Re-verify.** Confirm all gates pass.',
  '',
  '### Verification',
  '',
  '- [ ] All gates pass',
  '- [ ] Health score reported',
  '',
  '---',
  '',
  '## PROTO-ORG-5: Session Compounding',
  '',
  '> Review session output, detect patterns, execute improvements.',
  '',
  '### Goal',
  '',
  'Convert session learnings into durable improvements.',
  '',
  '### Steps',
  '',
  '1. **Review session.** Examine git diff of changes.',
  '2. **Detect patterns.** Look for repeated steps, unclear workflows, new heuristics.',
  '3. **Classify.** Tool candidate, protocol update, heuristic addition, or workflow refinement.',
  '4. **Prioritize.** Frequency x impact.',
  '5. **Execute.** Implement highest-priority improvement.',
  '6. **Verify.** `organon verify` and `organon health`.',
  '7. **Record observations.** If session revealed lasting insights.',
  '',
  '### Verification',
  '',
  '- [ ] At least one improvement identified',
  '- [ ] `organon verify` passes',
  '',
  '---',
  '',
  '## PROTO-ORG-6: Organon File Creation',
  '',
  '> Create valid organon files with correct placement and references.',
  '',
  '### Goal',
  '',
  'Produce a valid organon file with proper frontmatter, structure, and inheritance.',
  '',
  '### Steps',
  '',
  '1. **Classify scope.** Product, domain, feature, or component.',
  '2. **Check parent.** Load parent ETHOS.md, new file must inherit constraints.',
  '3. **Select template.** ETHOS, PHILOSOPHY, PROTOCOL, or README.',
  '4. **Determine placement.** Under organon/domains/ or organon/features/.',
  '5. **Generate frontmatter.** Type, scope, name, version, summary, token_estimate.',
  '6. **Write content.** Follow template section structure.',
  '7. **Validate.** `organon validate` on new file.',
  '8. **Check references.** `organon verify --gate triplets` for bidirectional refs.',
  '',
  '### Verification',
  '',
  '- [ ] `organon validate` passes',
  '- [ ] File in correct directory',
  '- [ ] Parent constraints inherited',
  '',
  '---',
  '',
  '## PROTO-ORG-7: Quality Review',
  '',
  '> Semantic review beyond automated gates.',
  '',
  '### Goal',
  '',
  "Find quality issues automation can't detect: vague invariants, misordered principles, inconsistent terminology.",
  '',
  '### Steps',
  '',
  '1. **Run automated gates.** `organon verify` and `organon validate`.',
  '2. **Review invariants.** Testable? Specific? Enforceable?',
  '3. **Review principles.** Genuinely prioritized? Conflict test passes?',
  '4. **Review identity.** Specific and distinguishing?',
  '5. **Review heuristics.** Cover actual recurring decisions?',
  '6. **Check anti-patterns.** Phantom enforcement, aspiration as invariant, etc.',
  '7. **Generate report.** Findings by severity with fix recommendations.',
  '',
  '### Verification',
  '',
  '- [ ] All automated gates pass',
  '- [ ] Every invariant passes "testable?" filter',
  '- [ ] No anti-pattern matches',
  '',
].join('\n');
